@rem assimp をライブラリビルドしておくためのbatファイルです
@rem
@rem ==== CONFIGURE ====
@cd %~dp0\assimp

@cmake -B build  -DASSIMP_BUILD_TESTS=OFF -DBUILD_SHARED_LIBS=OFF -DCMAKE_CONFIGURATION_TYPES=Debug;Release -DCMAKE_DEBUG_POSTFIX= -DLIBRARY_SUFFIX= -DASSIMP_WARNINGS_AS_ERRORS=OFF -DASSIMP_INSTALL=OFF -DASSIMP_BUILD_ZLIB=ON -DASSIMP_BUILD_ALL_EXPORTERS_BY_DEFAULT=OFF -DASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT=OFF -DASSIMP_BUILD_OBJ_IMPORTER=ON -DASSIMP_BUILD_GLTF_IMPORTER=ON

@rem ==== BUILD ====
@cmake --build build --config Debug
@cmake --build build --config Release

@cd ..

